/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Asset = IDL.Variant({
  'BNB' : IDL.Null,
  'BTC' : IDL.Null,
  'ETH' : IDL.Null,
  'ICP' : IDL.Null,
  'SOL' : IDL.Null,
  'TSLA' : IDL.Null,
  'USDT' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssetBalance = IDL.Record({
  'balance' : IDL.Float64,
  'asset' : Asset,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Direction = IDL.Variant({
  'receive' : IDL.Null,
  'send' : IDL.Null,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'direction' : Direction,
  'asset' : Asset,
  'note' : IDL.Text,
  'counterparty' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMockBalance' : IDL.Func([Asset, IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBalances' : IDL.Func([], [IDL.Vec(AssetBalance)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisplayName' : IDL.Func([], [IDL.Text], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeWallet' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'receiveAsset' : IDL.Func([Asset, IDL.Float64, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendAsset' : IDL.Func([Asset, IDL.Float64, IDL.Text, IDL.Text], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Asset = IDL.Variant({
    'BNB' : IDL.Null,
    'BTC' : IDL.Null,
    'ETH' : IDL.Null,
    'ICP' : IDL.Null,
    'SOL' : IDL.Null,
    'TSLA' : IDL.Null,
    'USDT' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssetBalance = IDL.Record({ 'balance' : IDL.Float64, 'asset' : Asset });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Direction = IDL.Variant({ 'receive' : IDL.Null, 'send' : IDL.Null });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'direction' : Direction,
    'asset' : Asset,
    'note' : IDL.Text,
    'counterparty' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMockBalance' : IDL.Func([Asset, IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBalances' : IDL.Func([], [IDL.Vec(AssetBalance)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisplayName' : IDL.Func([], [IDL.Text], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeWallet' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'receiveAsset' : IDL.Func([Asset, IDL.Float64, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendAsset' : IDL.Func([Asset, IDL.Float64, IDL.Text, IDL.Text], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };